blog/urls.py
from django.contrib import admin
from django.urls import path, include

from blog import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blogapp.urls', namespace='blogapp'))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogapp/urls.py
from django.urls import path
from . import views

app_name = 'blogapp'

urlpatterns = [
    path('services/', views.post_list, name='post_list'),
    path('post/<slug:slug>/', views.post_detail, name='post_detail'),
    path('', views.home, name='home'),
    # path('post/<slug:slug>/comments/', views.post_comment, name='post_comment')
    # path('success/', views.success_url, name='success_url'),
    path('contact/', views.contact_us, name='contact_us'),
    path('blog/', views.blog, name='blog'),
    path('projects/', views.project, name='projects')
]

blogapp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DR', 'Draft'
        PUBLISHED = 'PB', 'Published'

    class PublishedManager(models.Manager):
        def get_queryset(self):
            return super().get_queryset().filter(status=Post.Status.PUBLISHED)

    title = models.CharField(max_length=300, verbose_name='title')
    slug = models.SlugField(max_length=300,verbose_name='slug')
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts', verbose_name='author')
    image = models.ImageField(upload_to='blog/%Y/%m/%d/', blank=True, null=True, verbose_name='image')
    body = models.TextField(verbose_name='text')
    publish = models.DateTimeField(default=timezone.now, verbose_name='publish')
    created = models.DateTimeField(auto_now_add=True, verbose_name='created')
    updated = models.DateTimeField(auto_now_add=True, verbose_name='updated')
    status = models.CharField(max_length=2, choices=Status.choices, default=Status.DRAFT, verbose_name='status')

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ('-publish',)
        indexes = [
            models.Index(fields=['title'])
        ]
    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80, verbose_name='name')
    email = models.EmailField()
    body = models.TextField(verbose_name='text')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=False)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'comment by {self.name} on {self.post}'


class ContactUs(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField()
    subject = models.CharField(max_length=80)
    message = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    answer_admin = models.TextField(null=True, blank=True)
    read = models.BooleanField(default=False)

    class Meta:
        ordering = ['created']
        verbose_name = "Contact us"
        verbose_name_plural = "Contact us"

    def __str__(self):
        return f'{self.name} by {self.email} on {self.subject}'


class Project(models.Model):
    title = models.CharField(max_length=80, verbose_name='project title')
    employer = models.CharField(max_length=80, verbose_name='employer')
    image = models.ImageField(upload_to='projects/', null=True, blank=True, verbose_name='project image')
    video = models.FileField(upload_to='videos/', verbose_name='video file', null=True, blank=True)
    date = models.CharField(max_length=80, verbose_name='date published project')
    language = models.CharField(max_length=100, verbose_name='project language')
    preview = models.URLField(verbose_name='project preview')

    def __str__(self):
        return f'{self.title} for {self.employer}'

blogapp/forms.py
from django.forms import ModelForm, forms
from .models import Comment, ContactUs

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class ContactForm(ModelForm):
    class Meta:
        model = ContactUs
        fields = ['name', 'email', 'subject', 'message']

blogapp/views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.decorators.http import require_POST

from .models import Post, Comment, Project
from django.http import Http404
from .forms import CommentForm, ContactForm

def post_list(request):
    post_list = Post.published.all()
    paginator = Paginator(post_list, 6)
    page_number = request.GET.get('page', 1)
    posts = paginator.get_page(page_number)
    return render(request, 'blogapp/post_list.html', {'posts': posts})

# def post_detail(request, id):
#     try:
#         post = Post.published.get(id=id)
#     except Post.DoesNotExist:
#         raise Http404('No Post Found')
#     # post = get_object_or_404(Post, id=id, status=Post.Status.PUBLISHED)
#
#     return render(request, 'blogapp/post_detail.html', {'post': post})

# def post_detail(request, slug):
#     try:
#         post = Post.published.get(slug=slug)
#     except Post.DoesNotExist:
#         raise Http404('No Post Found')
#     # post = get_object_or_404(Post, id=id, status=Post.Status.PUBLISHED)
#
#     return render(request, 'blogapp/post_detail.html', {'post': post})

def home(request):
   return render(request, 'blogapp/home.html')

# @require_POST
# def post_comment(request, slug):
#     # post = get_object_or_404(Post, slug=slug, status='published')
#     post = Post.published.get(slug=slug)
#     comment = None
#     form = CommentForm(data=request.POST)
#     if form.is_valid():
#         comment = form.save(commit=False)
#         comment.post = post
#         comment.save()
#     return render(request, 'blogapp/post_detail.html', {
#         'post': post, 'form': form, 'comment': comment
#     })

def post_detail(request, slug):
    try:
        post = Post.published.get(slug=slug)
    except Post.DoesNotExist:
        raise Http404('No Post Found')

    active_comments = post.comments.filter(active=True)
    active_comments_count = post.comments.filter(active=True).count()

    comment = None
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.save()
            # Clear the form after successful submission
            form = CommentForm()
            return render(request, 'blogapp/success_sending_message.html')
    else:
        form = CommentForm()

    return render(request, 'blogapp/post_detail.html', {
        'post': post,
        'form': form,
        'comment': comment,
        'active_comments': active_comments,
        'active_comments_count': active_comments_count
    })

# def success_url(request):
#     return render(request, 'blogapp/success_sending_message.html')

# def contact_us(request):
#     if request.method == 'POST':
#         form = ContactForm(request.POST)
#         if form.is_valid():
#             form.save()
#             # return render(request, 'blogapp/success_sending_message.html')
#     else:
#         form = ContactForm()
#
#     return render(request, 'blogapp/contact_us.html', {'form': form})





def contact_us(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            # Optionally, you can add a success message here
            return render(request, 'blogapp/success_sending_message.html')  # Replace 'success_url' with the URL name of your success page
    else:
        form = ContactForm()

    return render(request, 'blogapp/contact_us.html', {'form': form})


def blog(request):
    post_list = Post.published.all()
    paginator = Paginator(post_list, 3)
    page_number = request.GET.get('page', 1)
    posts = paginator.get_page(page_number)
    return render(request, 'blogapp/blog.html', {'posts': posts, 'current_page': int(page_number)})

def project(requset):
    projects = Project.objects.all()
    return render(requset, 'blogapp/projects.html', {'projects': projects})

blogapp/templates/blogapp/base.html
<!DOCTYPE html>
<html class="overflow-x-hidden h-full" lang="en">
   <head>
      <meta charset="utf-8">
      <title>Tunis - Tailwind CSS Personal Portfolio HTML Template</title>
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- Template Google Fonts -->
      <link href="https://fonts.googleapis.com/css?family=Poppins:400,500,600,700,800,900" rel="stylesheet">
      <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet">
      <!-- Template CSS Files -->
      <link rel="stylesheet" href="/static/assets/css/circle.css" >
      <link rel="stylesheet" href="/static/assets/css/font-awesome.min.css">
      <link rel="stylesheet" href="/static/assets/css/component.css">
      <link rel="stylesheet" href="/static/assets/css/style.css">
      <!-- CSS Skin File -->
      <link rel="stylesheet" href="/static/assets/css/skins/yellow.css">
      <!-- Live Style Switcher - demo only -->
      <link rel="alternate stylesheet" type="text/css" title="blue" href="/static/assets/css/skins/blue.css">
      <link rel="alternate stylesheet" type="text/css" title="green" href="/static/assets/css/skins/green.css">
      <link rel="alternate stylesheet" type="text/css" title="yellow" href="/static/assets/css/skins/yellow.css">
      <link rel="alternate stylesheet" type="text/css" title="blueviolet" href="/static/assets/css/skins/blueviolet.css">
      <link rel="alternate stylesheet" type="text/css" title="goldenrod" href="/static/assets/css/skins/goldenrod.css">
      <link rel="alternate stylesheet" type="text/css" title="magenta" href="/static/assets/css/skins/magenta.css">
      <link rel="alternate stylesheet" type="text/css" title="orange" href="/static/assets/css/skins/orange.css">
      <link rel="alternate stylesheet" type="text/css" title="purple" href="/static/assets/css/skins/purple.css">
      <link rel="alternate stylesheet" type="text/css" title="red" href="/static/assets/css/skins/red.css">
      <link rel="alternate stylesheet" type="text/css" title="yellowgreen" href="/static/assets/css/skins/yellowgreen.css">
      <link rel="stylesheet" type="text/css" href="/static/assets/css/styleswitcher.css">
      <link rel="icon" href="/static/assets/img/img.png" type="image/x-icon">
      <!-- Modernizr JS File -->
      <script src="/static/assets/js/modernizr.min.js"></script>
   </head>
   <body class="home dark font-Poppins text-fs-16 text-white font-medium leading-lh-1.6 relative w-full h-full bg-black overflow-hidden">
      <!-- Preloader Starts -->
      <div id="preloader" class="fixed z-100 group left-0 top-0 h-screen w-full flex justify-center items-center pointer-events-none before:absolute before:left-0 before:top-0 before:w-1/2 before:h-full before:bg-black-3 before:transition-all before:duration-300 after:absolute after:right-0 after:top-0 after:w-1/2 after:h-full after:bg-black-3 after:transition-all after:duration-300 [&.preloaded]:before:animate-finishanimation [&.preloaded]:after:animate-finishanimation">
         <div class="line m-0 h-250 w-3 rounded-4 relative overflow-hidden transition-all duration-700 before:animate-animateline before:z-10 before:absolute before:left-0 before:top-1/2 before:w-3 before:h-0 before:-translate-y-1/2 after:animate-animatebgline after:absolute after:left-0 after:w-1 after:h-full after:bg-transparent after:-translate-y-full group-[.preloaded]:opacity-0 group-[.preloaded]:!h-full group-[.preloaded]:after:opacity-0"></div>
      </div>
      <!-- Preloader Ends -->
      <!-- Header Starts -->
      <header class="header from-lg:fixed from-lg:right-30 from-lg:bottom-0 from-lg:z-30 from-lg:flex from-lg:items-center from-lg:h-[calc(100vh-200px)] from-lg:top-100 from-lg:opacity-100 from-lg:transition from-lg:duration-300 from-lg:[&.hide-header]:z-0 from-lg:[&.hide-header]:opacity-0" id="navbar-collapse-toggle">
         <!-- Fixed Desktop Navigation Starts -->
         <ul id="desktop-nav" class="icon-menu down-lg:hidden from-md:block uppercase">
            <li class="desktop-nav-element cursor-pointer w-50 h-50 relative flex items-center transition duration-300 my-20 mx-0 rounded-full bg-black-2 active">
              <a href="{% url 'blogapp:home' %}">
                  <box-icon class="absolute left-0 right-0 mx-auto block text-center top-15 pointer-events-none text-fs-19" name="home" type="solid" color="#ffffff"></box-icon>
                  <div class="group block p-0 w-50 h-50" >
                  <h2 class="absolute text-center -z-10 block h-50 pr-25 pl-30 text-fs-15 right-0 opacity-0 text-white leading-lh-50 font-medium transition-all duration-300 rounded-30 group-hover:opacity-100 group-hover:right-27 group-hover:rounded-tl-30 group-hover:rounded-bl-30 group-hover:rounded-tr-none group-hover:rounded-br-none">Home</h2>
                  </div>
              </a>
            </li>
            <li class="desktop-nav-element cursor-pointer w-50 h-50 relative flex items-center transition duration-300 my-20 mx-0 rounded-full bg-black-2">
               <a href="{% url 'blogapp:post_list' %}">
                  <box-icon class="absolute left-0 right-0 mx-auto block text-center top-15 pointer-events-none text-fs-19" name="grid-alt" type="solid" color="#ffffff"></box-icon>
                  <div class="group block p-0 w-50 h-50" >
                  <h2 class="absolute text-center -z-10 block h-50 pr-25 pl-30 text-fs-15 right-0 opacity-0 text-white leading-lh-50 font-medium transition-all duration-300 rounded-30 group-hover:opacity-100 group-hover:right-27 group-hover:rounded-tl-30 group-hover:rounded-bl-30 group-hover:rounded-tr-none group-hover:rounded-br-none">Services</h2>
                  </div>
               </a>
            </li>
            <li class="desktop-nav-element cursor-pointer w-50 h-50 relative flex items-center transition duration-300 my-20 mx-0 rounded-full bg-black-2">
               <a href="{% url 'blogapp:projects' %}">
                  <box-icon class="absolute left-0 right-0 mx-auto block text-center top-15 pointer-events-none text-fs-19" name="briefcase-alt-2" type="solid" color="#ffffff"></box-icon>
                  <div class="group block p-0 w-50 h-50">
                  <h2 class="absolute text-center -z-10 block h-50 pr-25 pl-30 text-fs-15 right-0 opacity-0 text-white leading-lh-50 font-medium transition-all duration-300 rounded-30 group-hover:opacity-100 group-hover:right-27 group-hover:rounded-tl-30 group-hover:rounded-bl-30 group-hover:rounded-tr-none group-hover:rounded-br-none">Projects</h2>
               </div>
               </a>
            </li>
            <li class="desktop-nav-element cursor-pointer w-50 h-50 relative flex items-center transition duration-300 my-20 mx-0 rounded-full bg-black-2">
               <a href="{% url 'blogapp:blog' %}">
                  <box-icon class="absolute left-0 right-0 mx-auto block text-center top-15 pointer-events-none text-fs-19" name="detail" type="solid" color="#ffffff"></box-icon>
                  <div class="group block p-0 w-50 h-50">
                  <h2 class="absolute text-center -z-10 block h-50 pr-25 pl-30 text-fs-15 right-0 opacity-0 text-white leading-lh-50 font-medium transition-all duration-300 rounded-30 group-hover:opacity-100 group-hover:right-27 group-hover:rounded-tl-30 group-hover:rounded-bl-30 group-hover:rounded-tr-none group-hover:rounded-br-none">Blog</h2>
               </div>
               </a>
            </li>
            <li class="desktop-nav-element cursor-pointer w-50 h-50 relative flex items-center transition duration-300 my-20 mx-0 rounded-full bg-black-2">
               <a href="{% url 'blogapp:contact_us' %}">
                  <box-icon class="absolute left-0 right-0 mx-auto block text-center top-15 pointer-events-none text-fs-19" name="envelope" type="solid" color="#ffffff"></box-icon>
                  <div class="group block p-0 w-50 h-50">
                  <h2 class="absolute text-center -z-10 block h-50 pr-25 pl-30 text-fs-15 right-0 opacity-0 text-white leading-lh-50 font-medium transition-all duration-300 rounded-30 group-hover:opacity-100 group-hover:right-27 group-hover:rounded-tl-30 group-hover:rounded-bl-30 group-hover:rounded-tr-none group-hover:rounded-br-none">Contact</h2>
               </div>
               </a>
            </li>
         </ul>
         <!-- Fixed Desktop Navigation Ends -->
         <!-- Mobile Menu Starts -->
         <nav class="hidden down-md:block relative">
            <div id="menuToggle" class="fixed top-30 right-30 z-50 select-none pt-19 pl-16 w-54 h-54 rounded-5 bg-black-3 xs:right-15 xs:top-4 xs:pb-13 xs:w-49 xs:h-49">
               <input id="inputmobile" class="h-54 w-54 absolute top-0 left-0 opacity-0 z-20 cursor-pointer peer" type="checkbox">
               <span class="flex h-0.5 w-23 mb-5 relative bg-white z-10 rounded-3 origin-0 custom-transition peer-checked:rotate-45 peer-checked:translate-x-1 peer-checked:translate-y-0"></span>
               <span class="flex h-0.5 w-23 mb-5 relative bg-white z-10 rounded-3 origin-0-100 custom-transition peer-checked:opacity-0 peer-checked:scale-0-2"></span>
               <span class="flex h-0.5 w-23 mb-5 relative bg-white z-10 rounded-3 origin-0-100 custom-transition peer-checked:-rotate-45 peer-checked:translate-x-2 peer-checked:translate-y-2"></span>
               <ul class="fixed m-0 left-0 top-0 w-full h-full pt-60 bg-black-3 -translate-x-full ease-menu-mobile duration-500 peer-checked:transform-none [&>li]:cursor-pointer [&>li]:after:absolute [&>li]:after:h-px [&>li]:after:w-[calc(100%-60px)] [&>li]:after:bg-black-4 [&>li]:after:left-30 [&>li:last-child]:after:hidden" id="mobile-nav">
                  <li class="mobile-nav-element active relative pl-30 home-link">
                     <a href="{% url 'blogapp:home' %}">
                        <div class="uppercase delay-2000 no-underline relative text-fs-26 xs:text-fs-18 py-14">
                        <box-icon class="" name="home" type="solid" color="#ffffff"></box-icon>
                        <span class="absolute left-50 xs:left-35 font-normal">Home</span>
                     </div>
                     </a>
                  </li>
                  <li class="mobile-nav-element relative pl-30">
                     <a href="{% url 'blogapp:post_list' %}">
                        <div class="uppercase delay-2000 no-underline relative text-fs-26 xs:text-fs-18 py-14">
                        <box-icon class="" name="grid-alt" type="solid" color="#ffffff"></box-icon>
                        <span class="absolute left-50 xs:left-35 font-normal">Services</span>
                        </div>
                     </a>
                  </li>
                  <li class="mobile-nav-element relative pl-30">
                     <a href="{% url 'blogapp:projects' %}">
                        <div class="uppercase delay-2000 no-underline relative text-fs-26 xs:text-fs-18 py-14">
                        <box-icon class="" name="briefcase-alt-2" type="solid" color="#ffffff"></box-icon>
                        <span class="absolute left-50 xs:left-35 font-normal">Projects</span>
                        </div>
                     </a>
                  </li>
                  <li class="mobile-nav-element relative pl-30">
                     <a href="{% url 'blogapp:blog' %}">
                        <div class="uppercase delay-2000 no-underline relative text-fs-26 xs:text-fs-18 py-14">
                        <box-icon class="" name="detail" type="solid" color="#ffffff"></box-icon>
                        <span class="absolute left-50 xs:left-35 font-normal">Blog</span>
                        </div>
                     </a>
                  </li>
                  <li class="mobile-nav-element relative pl-30">
                     <a href="{% url 'blogapp:contact_us' %}">
                        <div class="uppercase delay-2000 no-underline relative text-fs-26 xs:text-fs-18 py-14">
                        <box-icon class="" name="envelope" type="solid" color="#ffffff"></box-icon>
                        <span class="absolute left-50 xs:left-35 font-normal">Contact</span>
                        </div>
                     </a>
                  </li>
               </ul>
            </div>
         </nav>
         <!-- Mobile Menu Ends -->
      </header>
      <!-- Header Ends -->

      {% block content %} {% endblock %}

      <!-- Template JS Files -->
      <script src="/static/assets/js/jquery-3.7.1.min.js"></script>
      <script src="/static/assets/js/styleswitcher.js"></script>
      <script src="/static/assets/js/imagesloaded.pkgd.min.js"></script>
      <script src="/static/assets/js/masonry.pkgd.min.js"></script>
      <script src="/static/assets/js/classie.js"></script>
      <script src="/static/assets/js/main.js"></script>
      <script src="/static/assets/js/cbpGridGallery.js"></script>
      <script src="/static/assets/js/jquery.hoverdir.js"></script>
      <script src="/static/assets/js/menu.js"></script>
      <script src="/static/assets/js/custom.js"></script>
      <script src="/static/assets/js/modernizr.min.js"></script>
      <script src="https://unpkg.com/boxicons@2.1.4/dist/boxicons.js"></script>
   </body>
</html>

blogapp/templates/blogapp/blog.html
{% extends 'blogapp/base.html' %}

{% block content %}
<div class="w-full h-full pages overflow-hidden">
    <!-- Blog Starts -->
    <div class="page page--current" id="blog">
        <div class="w-full">
            <!-- Section Title Starts -->
            <div class="mx-auto w-full relative py-80 text-center xs:px-25 xs:pt-16 xs:pb-14 xs:bg-black-3 xs:border-b xs:border-black-4 xs:fixed xs:left-0 xs:right-0 xs:top-0 xs:z-20">
                <h2 class="text-fs-56 font-black font-Poppins uppercase text-white m-0 xs:text-fs-26 xs:text-left xs:leading-lh-1.2">
                    mag. & <span class="text-accent">blog</span>
                </h2>
                <span class="text-fs-110 absolute left-0 right-0 top-1/2 tracking-10 leading-lh-0.7 font-extrabold text-muted -translate-y-1/2 uppercase xs:hidden">posts</span>
            </div>
            <!-- Section Title Ends -->
            <div class="xl:max-w-1140 lg:max-w-960 md:max-w-720 sm:max-w-540 xs:max-w-full mx-auto">
                <!-- Blog Posts Starts -->
                <div class="flex flex-wrap down-sm:flex-col">
                    {% for post in posts %}
                    <!-- Blog Post Starts -->
                    <div class="w-1/3 down-xl:w-1/2 down-sm:w-full px-16 xs:px-0 mb-30">
                        <div class="h-full bg-black-3 rounded-5">
                            <div class="rounded-t-5 cursor-pointer post-thumb">
                                <a href="{% url 'blogapp:post_detail' slug=post.slug  %}" class="rounded-t-5 relative overflow-hidden block group outline-0 transition-all duration-300">
                                    {% if post.image %}
                                    <img class="rounded-t-5 transition-all duration-300 group-hover:scale-125" src="{{ post.image.url }}" alt="">
                                    {% endif %}
                                </a>
                            </div>
                            <div class="bg-black-3 pt-20 px-25 pb-25 rounded-b-5">
                                <a href="{% url 'blogapp:post_detail' slug=post.slug  %}" class="leading-lh-26 text-fs-20 font-semibold text-accent-hover transition duration-300">
                                    {{ post.title }}
                                </a>
                                <p class="mt-15 mb-5 font-Open-sans">
                                    {{ post.body|truncatewords:20 }}
                                </p>
                                <span class="text-white text-fs-12 py-1 inline-block mb-12 rounded-20 font-semibold bg-black-3 opacity-80 font-Open-sans uppercase">
                                    {{ post.publish|date:"M d, Y" }} - By {{ post.author }}
                                </span>
                            </div>
                        </div>
                    </div>
                    <!-- Blog Post Ends -->
                    {% endfor %}
                </div>
                <!-- Blog Pagination Starts -->
                <nav class="mt-24">
                    <ul class="flex justify-center from-sm:mb-100 down-sm:mb-60 paginations">
                        {% for num in posts.paginator.page_range %}
                        <li>
                            <a href="?page={{ num }}" class="pagination-circle {% if num == current_page %} bg-accent {% else %} bg-black-3 {% endif %} bg-accent-hover rounded-full mx-5">{{ num }}</a>
                        </li>
                        {% endfor %}
                    </ul>
                </nav>
                <!-- Blog Pagination Ends -->
            </div>
        </div>
    </div>
    <!-- Blog Ends -->
</div>
{% endblock %}

blogapp/templates/blogapp/home.html
{% extends 'blogapp/base.html' %}

{% block content %}
<!-- Main Content Starts -->
<div class="w-full h-full pages overflow-hidden">
    <!-- Home Starts -->
    <div class="page page--current" id="home">
        <div class="bg-accent fixed w-full h-200prcnt -rotate-15 -top-1/2 -left-83prcnt hidden from-lg:block"></div>
        <div class="flex items-center h-screen w-full down-lg:mx-auto down-lg:justify-center xs:text-left down-lg:text-center ">
            <!-- Desktop Image Starts -->
            <video class="hidden from-lg:block fixed w-1/3 h-[calc(100vh-80px)] left-40 top-40 rounded-30 shadow-1 object-cover" autoplay loop muted>
                <source src="/static/assets/img/880744%20(online-video-cutter.com).mp4" type="video/mp4">
            </video>
            <!-- Desktop Image Ends -->
            <div class="from-lg:ml-100/3 from-lg:w-2/3">
                <div class="mx-auto max-w-550 custom-md-1:max-w-450">
                    <div class="video-container">
                        <video class="hidden down-lg:block rounded-full object-cover w-full h-full border-4 border-solid border-black-3" autoplay loop muted playsinline>
                            <source src="/static/assets/img/880744%20(online-video-cutter.com).mp4" type="video/mp4">
                        </video>
                    </div>
                    <!-- Mobile Image Ends -->
                    <!-- Informations Starts -->
                    <h1 class="text-fs-51 text-accent font-Poppins relative  font-bold leading-lh-62 pl-70 before:absolute before:left-0 before:top-29 before:h-4 before:w-40 before:rounded-10 custom-md-2:text-fs-42 down-xl:before:hidden down-xl:pl-0 custom-md-2:leading-lh-52 down-md:text-fs-38 down-md:leading-lh-48 down-md:mt-29 down-md:mb-13 xs:text-fs-29 xs:leading-lh-39 xs:mt-18">This is HashChain.<span class="block text-white">Knowledge enterprise</span></h1>
                    <p class="font-Open-sans mt-15 mb-28 leading-lh-35 down-lg:mt-2.5 down-lg:mb-23 down-lg:text-fs-15 down-lg:leading-lh-30">Spot a big, ambitious, challenge or opportunity in your industry. We start assessing whether a blockchain is even needed. Is there blockchain-fit? Blockchain-fit often lends itself to issues of (lack of) sharing, organizing and validating data between multiple parties.</p>
                    <a href="{% url 'blogapp:post_list' %}">
                        <div id="link-about" class="button cursor-pointer overflow-hidden inline-block leading-lh-1.4 rounded-30 text-ellipsis text-center align-middle select-none transition-all duration-250 ease-in-out uppercase no-underline relative z-10 py-16 pr-70 pl-35 text-fs-15 font-semibold text-white bg-transparent outline-0 before:absolute before:-z-10 before:left-0 before:right-0 before:top-0 before:bottom-0 before:translate-x-full hover:before:translate-x-0 before:transition before:duration-300 before:ease-out">
                            <span class="relative z-20 text-white">more about us</span>
                            <span class="absolute -right-px bottom-0 w-55 h-55 flex items-center justify-center rounded-full text-white text-fs-19 bg-accent">
                                <box-icon type='solid' name='chevrons-right' color="#ffffff"></box-icon>
                            </span>
                        </div>
                    </a>
                    <!-- Informations Ends -->
                </div>
            </div>
        </div>
    </div>
    <!-- Home Ends -->
    <!-- Blog Ends -->
</div>
<!-- Main Content Ends -->
{% endblock %}